export const SET_INGREDIENTS = 'SET_INGREDIENTS';

export const SEARCH_FOR_RECEIPES_START = 'SEARCH_FOR_RECEIPES_START';
export const SEARCH_FOR_RECEIPES_SUCESS = 'SEARCH_FOR_RECEIPES_SUCESS';
export const SEARCH_FOR_RECEIPES_FAIL = 'SEARCH_FOR_RECEIPES_FAIL';
