name: Mywebsite.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          npm ci
          npm run build
          npm test
          cd ..
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart

      # - name: Deploy with gh-pages
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # cypress-run:
  #   name: Cypress run
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [21.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run cy:run
