name: Mywebsite.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Check npm dependencies cache
      - name: Check if cache exists
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env-cache-name }}-${{ hashFiles('**/package-lock.json') }}

      # Install dependencies using npm ci
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      # Cache build artifacts cache
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: ~/build
          key: ${{ runner.os }}-build-${{ hashFiles('**/build/**') }}

      - name: build project
        run: |
          npm run build

      - name: restart server
        run: |
          pm2 stop 0 || true
          pm2 start 0
          pm2 save
          sudo service nginx restart

      - name: Set Api Key env variable
        run: echo "SPOON_API_KEY=${{ secrets.SPOON_API_KEY }}" >> .env

      # - name: Deploy with gh-pages
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # cypress-run:
  #   name: Cypress run
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [21.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run cy:run
